version: '3'

services:
  iching-app:
    container_name: iching-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
    environment:
      - NODE_ENV=production
      - PORT=4500
      - HOSTNAME=0.0.0.0
      - TZ=Asia/Shanghai
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4500"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"